/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_msdk_api_WGQQGroupObserverForSO */

#ifndef _Included_com_tencent_msdk_api_WGQQGroupObserverForSO
#define _Included_com_tencent_msdk_api_WGQQGroupObserverForSO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_msdk_api_WGQQGroupObserverForSO
 * Method:    OnQueryGroupInfoNotify
 * Signature: (Lcom/tencent/msdk/api/QQGroupRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_api_WGQQGroupObserverForSO_OnQueryGroupInfoNotify
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_tencent_msdk_api_WGQQGroupObserverForSO
 * Method:    OnBindGroupNotify
 * Signature: (Lcom/tencent/msdk/api/QQGroupRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_api_WGQQGroupObserverForSO_OnBindGroupNotify
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_tencent_msdk_api_WGQQGroupObserverForSO
 * Method:    OnUnbindGroupNotify
 * Signature: (Lcom/tencent/msdk/api/QQGroupRet;)V
 */
JNIEXPORT void JNICALL Java_com_tencent_msdk_api_WGQQGroupObserverForSO_OnUnbindGroupNotify
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
